### ISSUE TITLE
Missing mapping for "Sky" button

### ISSUE THREAD

**Issue by homeautomator** [Pulse-Eight/drivers#1]
The Control4 Driver for Sky Q / HD+ is missing the mapping for the "Sky" button which is on the remote.  The code for the sky button is 241 as per https://github.com/dalhundal/sky-remote/blob/master/sky-remote.js

**Comment by malard** [comment]
tvguide and sky buttons are doing the exact same thing. so there was no need to include both. Let me know if you think I am wrong on that?

**Comment by homeautomator** [comment]
What I am trying to do is to turn on the Sky box from standby as a conditional if it is in standby.

If I send the TV Guide button from Control4, when Sky box is in Standby, then it does not seem to work.

I cannot use the Power On command from Control4 as it seems to be a toggle on the sky box (if awake then sends Sky Box to standby, if on standby then turns on).

I assume driver does not have ability to query the Sky box standby status to set a variable so that I can do a conditional power on.

The only way I have found to turn on sky box from standby using a physical remote is to press the Sky button.  As the Sky button has a different code to TV guide, hence the request to modify driver and also include this as a button option.

Regards

**Comment by malard** [comment]
The driver already handles power management, see the Allow Power Off option.

But you can modify the driver and recompile it yourself in driverworks.

**Comment by homeautomator** [comment]
I am using the Sky+HD (sky_hd_ip_pulse-eight.c4z) driver.  On looking at the source code on GitHub, I think the Allow Power Off option is only implemented for Sky Q driver.

On Github, I also noticed that the source code for the Sky+HD (sky_hd_ip_pulse-eight.c4z) has been amended on 6th June 2018 and is version 6 but the published driver is dated 25th Jan 2018 and version 5.  I assume published driver directory needs to be updated with version 6?

Regards

Amit

**Comment by malard** [comment]
Sky HD does not feed back its power state, so I could not code this feature. I will check and see if I need to push updated published versions, but you can compile it yourself any time

**Comment by homeautomator** [comment]
OK Thanks.  Have locally compiled and version 6 driver is now responding to commands.

Have been playing with the IOS Sky+ app and interestingly it knows if a Sky+HD Box is in “Standy” or not.  I am making an assumption that there an undocumented way of querying this status, possibly through a UPnP service (https://gladdy.uk/blog/2012/08/18/sky-dnla-upnp-the-ipad-app-and-the-ip-control-protocol/).




Regards

**Comment by malard** [comment]
If you figure it out then why don't you add it in :)

From my phone

-------- Original Message --------
Subject: Re: [Pulse-Eight/drivers] Missing mapping for "Sky" button (#1)
