### ISSUE TITLE
Sky Q DVR Button?

### ISSUE THREAD

**Issue by amsound** [Pulse-Eight/drivers#2]
Hi, is it possible to have a DVR button for Control4 Sky Q IP driver? Thanks

**Comment by malard** [comment]
is that a button on the Control4 SR260 remote? if so, what should it map to on the Sky Q remote?

**Comment by amsound** [comment]
Yeah for the remote control. Weirdly, I had this as an IR code but can’t see a way of implementing it via IP!

**Comment by malard** [comment]
again, tell me which button on the remote this should be mapped too

**Comment by amsound** [comment]
Yes, the DVR button on the remote control, SR250/260

**Comment by amsound** [comment]
After some research I think this is the 'sky' button. Command 241. Be great if you could add that as a custom mapping on the properties tab?

**Comment by malard** [comment]
done
