### ISSUE TITLE
Set Channel Error

### ISSUE THREAD

**Issue by amsound** [Pulse-Eight/drivers#3]
Hi Martin, came across an issue with the C4 Sky Q driver, the set channel function doesn't seem to work. Thought I'd done something wrong but checked the Lua log. I get this for channel '101':

ReceivedFromProxy(): SET_CHANNEL on binding 5001; Call Function PRX_CMD.SET_CHANNEL()
ReceivedFromProxy: Unhandled command = SET_CHANNEL

**Comment by malard** [comment]
please explain how you call "SET_CHANNEL", provide an example project if possible

**Comment by amsound** [comment]
See example attached on Composer. This also seems to be the case if I used an SR-260 and select a channel from the RF_Sky list I populated.

<img width="344" alt="Screenshot 2020-11-09 071305" src="https://user-images.githubusercontent.com/74129410/98510607-52b69d80-225b-11eb-8f1e-f7a95d219fbd.png">
